DEFAULT_COUNT = 3
MAX_COUNT = 10
DEFAULT_TARGET_AGE = "5"
DEFAULT_TRUTH_MODE = "TRUTH"
DEFAULT_CULTURAL_CONTEXT = "RUSSIAN_FOLK"
DEFAULT_UTILITY_MODE = "NARRATIVE"

TARGET_AGE_MIN = 3
TARGET_AGE_MAX = 5
# Legacy global story length bounds; per-age enforcement uses AGE_STORY_LENGTH_POLICIES
# in src/core/stage2_length_policy.py (age 3: 3-4, age 5: 3-5).
STORY_SENTENCES_MIN = 3
STORY_SENTENCES_MAX = 5
MIN_QUESTIONS = 2
MAX_QUESTIONS = 3

USER_ARBITRATION_THRESHOLD = 3
MAX_VALIDATION_RETRIES = 5

MIN_CHILD_INDEX = 0.3
DEFAULT_IDEA_CHILD_INDEX = 0.5
FALLBACK_IDEA_CHILD_INDEX = 0.7
SCORE_NORMALIZATION_EPSILON = 0.2

VALIDATOR_CONTENT_PREVIEW_CHARS = 100
DEBUG_CONTENT_PREVIEW_CHARS = 80
DEBUG_TEXT_SEPARATOR_WIDTH = 60

DEFAULT_SAMPLER_COUNT = 1
STORY_IMAGE_FILENAME_TEMPLATE = "story_{index}.png"
IMAGE_FILE_EXTENSION = ".png"
QUESTION_NUMBERING_STRIP_CHARS = " 1234567890. -"
FORCE_APPROVE_COMMANDS = ("хватит", "достаточно", "больше не", "ок", "хорошо")

LLM_TEMPERATURE_DEFAULT = 0.7
LLM_TEMPERATURE_GENERATE_CANDIDATES = 0.9
LLM_TEMPERATURE_DEDUPLICATE_TOPICS = 0.2
LLM_TEMPERATURE_SCORE_CANDIDATES = 0.2
LLM_TEMPERATURE_VALIDATE_CANDIDATE = 0.2
LLM_TEMPERATURE_REFINE_CANDIDATE = 0.5

HTTP_REQUEST_TIMEOUT_SECONDS = 10
MEDIA_POLL_MAX_ATTEMPTS = 30
MEDIA_POLL_INTERVAL_SECONDS = 25
MEDIA_RETRY_INTERVAL_SECONDS = 10
IMAGE_ASPECT_RATIO = "1:1"

LOG_LEVEL = "DEBUG" # INFO DEBUG
LOG_TO_FILE = False
LOG_FILE_PATH = "logs/dreamydraw.log"
LOG_FORMAT_COLORED = True

LANGFUSE_HOST = "https://cloud.langfuse.com"
LANGFUSE_ENABLED = True
LANGFUSE_PROJECT_NAME = "dreamydraw"
LANGFUSE_ENV = "local"
LANGFUSE_SAMPLE_RATE = 1.0
LANGFUSE_CAPTURE_PROMPTS = False
LANGFUSE_PROMPT_PREVIEW_CHARS = 300
